### ISSUE TITLE
Help accessing the node using wpgraphql with gatsby-source-graphql

### ISSUE THREAD

**Issue by jerome281** [graysonhicks/gatsby-plugin-remote-images#15]
Hi,

I'm struggling accessing the node using wpgraphql with gatsby-source-graphql, any tips/suggestions. Here a screenshot of my file

![image](https://user-images.githubusercontent.com/6596071/61980886-eb39f780-afef-11e9-848c-aea64f909ab2.png)

Thank you

**Comment by graysonhicks** [comment]
Hi @jerome281 can you link to your gatsby-config for this project, or to the whole repo?

**Comment by graysonhicks** [comment]
Hi @jerome281 , after some digging, looks like this is caused by an underlying `gatsby-source-graphql` issue.  Check out the explanation in here: https://github.com/graysonhicks/gatsby-plugin-remote-images/issues/7#issuecomment-523456671.  Will re-test the plugin with it as soon as Gatsby changes that plugin.
