### ISSUE TITLE
Passing an array to imagePath

### ISSUE THREAD

**Issue by deadband** [graysonhicks/gatsby-plugin-remote-images#8]
Hi Grayson - great work on the plugin, thanks for putting this out for the community! Not really an issue with your plugin, but I was hoping maybe you could shed some light on something.

My question: Is it possible to pass an array of paths to imagePath? For example, the API I am trying to use has a response something like this:

"links": {
    "images": [
      "https://foo.com/image1.jpg",
      "https://foo.com/image2.jpg",
      "https://foo.com/image3.jpg",
      "https://foo.com/image4.jpg",
      "https://foo.com/image5.jpg",
      "https://foo.com/image6.jpg",
      "https://foo.com/image7.jpg",
    ]
  },

From what I understand, imagePath is looking for a singular path and not an array of paths. Am I trying to make it do something its not able to do or am I just overlooking something simple?

I went to the lodash docs for _.get but still had no luck. Thanks in advance!

**Comment by graysonhicks** [comment]
Hey @deadband, thanks for this!  This is a duplicate of [this issue](https://github.com/graysonhicks/gatsby-plugin-remote-images/issues/2), in which I recommended using multiple instances of the plugin, but I don't think that's the best solution long term.  I would love to add this functionality out of the box, I think it makes sense.  I don't have time this week to look at adding this, but PRs welcome and it's top of the list for features to add.

Thanks again!

**Comment by deadband** [comment]
Thanks for the response @graysonhicks, I will look into a way to accomplish this when I have a moment. The multiple instance approach may not work for me as I never know what the length of the array will be. I also agree with you that this would not be the cleanest approach. Once again, thanks for your contribution with this plugin!

**Comment by darrazo** [comment]
Hi @graysonhicks, @deadband,

Thanks a lot for the work on this plugin! I am quite new to gatsby ecosystem and I am definitely not a javascript expert but I tried to work on a similar feature since I needed it for a new project. In my case I need to handle this kind of schemas `
{
	b:[
		{
			imageUrl: "http://...."
		}
	]
}
`
I forked the project, the idea is that I look for all the images that correspond to the path in the node tree. I might be reinventing the wheel though.
NB: I also tried to use graphQL to query the images but in not possible at this build step:
https://github.com/gatsbyjs/gatsby/issues/3121

please feel free to add any comment or remark. I am not sure it is a PR material for now: here is the URL: https://github.com/darrazo/gatsby-plugin-remote-images/commit/b054601f51df72189781eb4d0806f38343b153d5
